### ISSUE TITLE
async-retriever bug

### ISSUE THREAD

**Issue by rmcd-mscb** [hyriver/async-retriever#41] opened 2022-12-22 15:08 UTC
### What happened?

async-retriever crashes when instantiating pynhd.NLDI.

### Minimal Complete Verifiable Example

```Python
# .yml

name: "gdptools-examples"
channels:
  - conda-forge
dependencies:
  - python>=3.9,<=3.10
  - pip
  - git
  - poetry
  - flopy
  - pydap
  - nodejs
  - jupyterlab
  - jupytext
  - shapely<2.0.0
  - pygeos
  - py3dep
  - pynhd
  - pygeohydro
  - pygeoogc
  - pygeoutils
  - async-retriever
  - hvplot
  - geoviews
  - cartopy
  - "holoviews[recommended]"
  - bokeh

I built env with mamba 0.22.1/conda 4.12.0.

Once env activated

from pynhd import NLDI
nldi = NLDI()
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
Python 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pynhd import NLDI
>>> nldi = NLDI()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rmcd/mambaforge/envs/gdptools-examples/lib/python3.10/site-packages/pynhd/pynhd.py", line 644, in __init__
    resp: list[dict[str, Any]] = self._get_url(  # type: ignore
  File "/home/rmcd/mambaforge/envs/gdptools-examples/lib/python3.10/site-packages/pynhd/pynhd.py", line 629, in _get_url
    resp = ar.retrieve_json([url], [{"params": payload}])
  File "/home/rmcd/mambaforge/envs/gdptools-examples/lib/python3.10/site-packages/async_retriever/async_retriever.py", line 452, in retrieve_json
    resp: list[dict[str, Any]] = retrieve(  # type: ignore
  File "/home/rmcd/mambaforge/envs/gdptools-examples/lib/python3.10/site-packages/async_retriever/async_retriever.py", line 253, in retrieve
    resp = [r for _, r in sorted(tlz.concat(results))]
  File "/home/rmcd/mambaforge/envs/gdptools-examples/lib/python3.10/site-packages/async_retriever/async_retriever.py", line 251, in <genexpr>
    results = (loop.run_until_complete(session(url_kwds=c)) for c in chunked_reqs)
  File "/home/rmcd/mambaforge/envs/gdptools-examples/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/rmcd/mambaforge/envs/gdptools-examples/lib/python3.10/site-packages/async_retriever/async_retriever.py", line 94, in async_session
    return await asyncio.gather(*tasks)  # type: ignore
  File "/home/rmcd/mambaforge/envs/gdptools-examples/lib/python3.10/site-packages/async_retriever/utils.py", line 62, in retriever
    async with session(url, **s_kwds) as response:
  File "/home/rmcd/mambaforge/envs/gdptools-examples/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/rmcd/mambaforge/envs/gdptools-examples/lib/python3.10/site-packages/forge/_revision.py", line 322, in inner
    return await callable(*mapped.args, **mapped.kwargs)
  File "/home/rmcd/mambaforge/envs/gdptools-examples/lib/python3.10/site-packages/aiohttp_client_cache/session.py", line 46, in _request
    response, actions = await self.cache.request(
  File "/home/rmcd/mambaforge/envs/gdptools-examples/lib/python3.10/site-packages/aiohttp_client_cache/backends/base.py", line 127, in request
    response = None if actions.skip_read else await self.get_response(actions.key)
  File "/home/rmcd/mambaforge/envs/gdptools-examples/lib/python3.10/site-packages/aiohttp_client_cache/backends/base.py", line 142, in get_response
    elif not await self.is_cacheable(response):  # type: ignore
  File "/home/rmcd/mambaforge/envs/gdptools-examples/lib/python3.10/site-packages/aiohttp_client_cache/backends/base.py", line 86, in is_cacheable
    'disabled method': str(response.method) not in self.allowed_methods,
AttributeError: 'CachedResponse' object has no attribute 'method'
```

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: 601b7d0b047237380769129cda9a35bf41eec07f
python: 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.4.0]
python-bits: 64
OS: Linux
OS-release: 5.10.16.3-microsoft-standard-WSL2
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.12.2
libnetcdf: 4.8.1

aiodns: 3.0.0
aiohttp: 3.8.3
aiohttp-client-cache: 0.7.3
aiosqlite: 0.18.0
async-retriever: 0.3.8
bottleneck: None
brotli: installed
click: 8.1.3
cytoolz: 0.12.0
dask: 2022.12.1
defusedxml: 0.7.1
folium: 0.14.0
geopandas: 0.12.2
hydrosignatures: 0.0.0
lxml: 4.9.2
matplotlib: 3.6.2
netCDF4: 1.6.2
networkx: 2.8.8
numba: 0.56.4
numpy: 1.23.5
owslib: 0.27.2
pandas: 1.5.2
py3dep: 0.13.9
pyarrow: 10.0.1
pydaymet: None
pygeohydro: 0.13.8
pygeoogc: 0.13.9
pygeos: 0.14
pygeoutils: 0.13.10
pynhd: 0.13.8
pyproj: 3.4.1
pytest: None
pytest-cov: None
rasterio: 1.3.4
requests: 2.28.1
requests-cache: 0.9.7
richdem: None
rioxarray: 0.13.3
scipy: 1.9.3
shapely: 1.8.5.post1
tables: None
ujson: 5.5.0
urllib3: 1.26.13
xarray: 2022.12.0
xdist: None
yaml: 6.0

</details>

**Comment by cheginit** [comment] 2022-12-22 18:22
Thanks for reporting this issue. Unfortunately, I cannot reproduce this error. I used the same env file that you mentioned and tried it on macOS and Linux, and they both worked fine without any issue. I compared the package versions that were installed in the env that I created with yours, and they were exactly the same. Maybe you're not activating the correct env?

As an aside, your `mamba` version is way outdated, the latest version is 1.1.0 which is their production version. So, I'd suggest updating yours.

**Comment by rmcd-mscb** [comment] 2022-12-22 19:45
Thanks Taher, I think I might have figured out the issue.  In my working folder there is a cache/ folder with aiohttp_cache.sqllite.  It must have become corrupted.  I realized if I used the environment in another folder it worked fine, but not in my working folder.  After deleting the .sqllite file - it works.  Just an FYI.

**Comment by cheginit** [comment] 2022-12-23 00:36
Ah, ok. Yeah, it's possible that a cache that was created with a previous version is not compatible with a newer version. Thanks for letting me know. I am going to close it for now, please reopen if the issue persists.

**Comment by rmcd-mscb** [comment] 2022-12-23 15:23
Taher - I'd been bumping into this problem for a while not understanding what the issue was.  Previously I'd been pinning the package versions to an older version to get it to work.  Wondering if there is a way you can clear the cache or ?  if there is an inconsistency automatically, otherwise won't this happen again?  Or maybe raising an error that informs the user.

**Comment by cheginit** [comment] 2022-12-23 17:10
I see. If that's something that happened to you several times, we should investigate. I never had this issue before, and I rarely delete caches for exactly catching these types of issues for testing purposes. There were some instances of cache corruption due to some network and sqlite issues that I had to delete, but never the issue that you had.

That said, can you tell me more about this issue, and what were the circumstances that you had this issue other than what you've already said? For example, if you know the version of `aiohttp-client-cache` (the package that `async-retriever` uses) that the existing cache was generated with. Based on the traceback that you submitted, it seems that a cached response that has been loaded does not have `.method` but when I checked `aiohttp-client-cache`, this [method](https://github.com/requests-cache/aiohttp-client-cache/blob/73fbd3988b13c8f1193019c29ed7a0523004bbde/aiohttp_client_cache/response.py#L57) has been there over the past couple of major versions.

Technically, URLs, keywords, and pickled responses are stored. So, my only guess is that, there can be a situation where there's a breaking change in `aiohttp-client-cache` that leads to loading a pickled object that's not compatible with the current version. But, I never bumped into this issue.

**Comment by cheginit** [comment] 2022-12-23 17:27
Regarding automatic handling of these types of errors, it's difficult to generalize and catch. I think it'd be best if users handle them on a case-by-case basis.

For deleting a certain cached request and response, you can use the [`delete_url_cache`](https://docs.hyriver.io/autoapi/async_retriever/async_retriever/index.html#async_retriever.async_retriever.delete_url_cache), please take a look at README of `async-retriever` for an example. But if you want to delete the whole cache, one way can be something like this:

```python
try:
    # some functions
except AttributeError as e:
    if "CachedResponse" in str(e):
        Path("cache", "aiohttp_cache.sqlite").unlink()
    # retry
```

Or you can simply disable caching altogether:

```python
import os

os.environ["HYRIVER_CACHE_DISABLE"] = "true"
```

**Closed** 2023-01-06 06:50 UTC
Labels: bug

**Comment by cheginit** [comment] 2023-01-06 14:23
@rmcd-mscb The issue seems to be related to a bug in `aiohttp-client-cache`. I was able to reproduce your error. After installing the latest version of `aiohttp-client-cache` which is v0.8.1. The issue was fixed. Please give it a try and let me know it solves the issue.
